version: '3.4'

services:
  authenticationservice:
    image: authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    ports:
      - 5007:443
      - 5006:80      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/authenticationservice.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  imageservice:
    image: imageservice
    build:
      context: .
      dockerfile: ImageService/Dockerfile
    ports:
      - 5005:443
      - 5004:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/imageservice.pfx
    volumes:
      - ~/.aspnet/https:/https:ro


  priceservice:
    image: priceservice
    build:
      context: .
      dockerfile: PriceService/Dockerfile
    ports:
      - 5003:443
      - 5002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/priceservice.pfx
    volumes:
      - ~/.aspnet/https:/https:ro


  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - 5001:443
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/productservice.pfx
      - API:ImageClientBaseAddress=https://host.docker.internal:5005
      - API:PriceClientBaseAddress=https://host.docker.internal:5003
    volumes:
      - ~/.aspnet/https:/https:ro

